apiVersion: apps/v1
kind: Deployment
metadata:
  name: testsite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testsite
  template:
    metadata:
      labels:
        app: testsite
    spec:
      containers:
      - name: testsite
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 80