replicaCount: 2

image:
  repository: maartenacademy/testsite
  tag: "10"  # Of specifieke versie zoals "9"
  pullPolicy: Always  # Belangrijk! Anders cached hij oude versie

service:
  type: ClusterIP
  port: 80